language: rust
sudo: false
rust:
- nightly
matrix:
  allow_failures:
  - rust: nightly
addons:
  apt:
    packages:
    - hunspell
install:
- nvm install 6
- rvm use 2.2.3 --install --binary --fuzzy
- gem install html-proofer
before_script:
- rustc --version
- node --version
- ruby --version
- gem --version
- htmlproofer --version
- hunspell -vv
script:
- make
- make test
- make html
- htmlproofer stage/_book --log-level error --only-4xx --check-html --url-ignore "#"
notifications:
  email:
  - shaposhnikigor95@bk.ru
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
branches:
  only: master
env:
  global:
  - secure: cwKUZkQrKNQhA5ZVy/CCEVEvHEW0zZG8sIzADVG6zwLgtnss8Ayl3XMZyMSEQA1awXYrjhzocxDw2cJDFsKe1ftpPJPCc7xPXbiDx0eLm5MdAi+d+ouogiPRRKzaSGgcHSmPh2esGq63zkRYDDa5wsIrsv8s+W7+hL4HvqwXOpRuSqJJy9hgYKqgGITeraaz47aN+vUJV3Ve+viTe8FJu3ZSBaS5ey0gw4Ra3sbchq+GbRmSRiT/Nsl0CyvBTCg0saJUVP6bK72xJu/sqHMrydzmDSiV7blqFzA4dZWSRP3rTIu3Ttrj+aeYmiC46hiQthFllJP8mHyipXcgE7883ONLeD3GxqzRw6VpEYiEwgFTc3BESJqdcR/LmsdCsgBz3roSIZTR/c2kGTEntoUlXaixFQ4wPEaMJSc+spsBZcMpkQvKgUYeeb12hyIrOtQSwEfS3TA/XmulIhoZOpSiRc3Th9yuZtToVa7LOGwhkzdn+kD7B2LPbyVCiopFSLfhfRgehPQI95RIcf9hhGJRg7XZEFMMq0SbKQgDpeb612A/Uf6gwglVRKarX/iXCHBSXjubBbRcPlpmWMHVCT53oOT1kjQmnVgePW3uT9Xv4dntX/phYQYa+x+rAjBdyvY8cNgKV74gw8sJCrC4whZRGNHXc6P3n7FJpUcxxtWTszY=
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
